title: Tablet
button_card_templates: !include button_card_templates_data.yaml
views:
  - !include home.yaml
  - !include media.yaml
  - !include security.yaml
  - !include weather.yaml
  - !include server.yaml
  - !include printers.yaml
